StartupEvents.registry('item', e => {
	e.create('godly_shard_flaming').displayName('Flaming Godly Shard').rarity('EPIC')
	e.create('godly_shard_toxic').displayName('Toxic Godly Shard').rarity('EPIC')
	e.create('godly_shard_end').displayName('Ender Godly Shard').rarity('EPIC')
	e.create('godly_shard_abyssal').displayName('Abyssal Godly Shard').rarity('EPIC')
	e.create('godly_shard_strange').displayName('Strange Godly Shard').rarity('EPIC')
	e.create('godly_shard_flaming_charged').displayName('Charged Flaming Shard').rarity('EPIC')
	e.create('godly_shard_toxic_charged').displayName('Charged Toxic Shard').rarity('EPIC')
	e.create('godly_shard_end_charged').displayName('Charged Ender Shard').rarity('EPIC')
	e.create('godly_shard_abyssal_charged').displayName('Charged Abyssal Shard').rarity('EPIC')
	e.create('godly_shard_strange_charged').displayName('Charged Strange Shard').rarity('EPIC')
	e.create('godly_alloy_mana_attuned').displayName('Mana Attuned Godly Alloy').rarity('EPIC')
	e.create('partial_godly_alloy_fluid_attuned', 'create:sequenced_assembly').displayName('Partially Fluid Attuned Godly Alloy').rarity('EPIC')
	e.create('godly_alloy_fluid_attuned').displayName('Fluid Attuned Godly Alloy').rarity('EPIC')
	e.create('godly_alloy_unstable').displayName('Unstable Godly Alloy').rarity('EPIC')
	e.create('godly_alloy_energy_attuned').displayName('Energy Attuned Godly Alloy').rarity('EPIC')
	e.create('incomplete_creative_pool', 'create:sequenced_assembly').displayName('Incomplete Guilty Pool').rarity('EPIC')
	e.create('incomplete_godly_alloy_energy_attuned').displayName('Incomplete Energy Godly Alloy').rarity('EPIC')
	e.create('incomplete_creative_motor', 'create:sequenced_assembly').displayName('Incomplete Creative Motor').rarity('EPIC')
	e.create('incomplete_creative_tank', 'create:sequenced_assembly').displayName('Incomplete Creative Tank').rarity('EPIC')
	e.create('almost_complete_creative_tank').displayName('Almost Complete Creative Tank').rarity('EPIC')
	e.create('almost_complete_creative_motor').displayName('Almost Complete Creative Motor').rarity('EPIC')
	e.create('almost_complete_creative_pool').displayName('Almost Complete Creative Pool').rarity('EPIC')
})
