StartupEvents.registry('item', e => {
	e.create('godly_shard_flaming').displayName('Flaming Godly Shard').rarity('EPIC')
	e.create('godly_shard_toxic').displayName('Toxic Godly Shard').rarity('EPIC')
	e.create('godly_shard_end').displayName('Ender Godly Shard').rarity('EPIC')
	e.create('godly_shard_abyssal').displayName('Abyssal Godly Shard').rarity('EPIC')
	e.create('godly_shard_strange').displayName('Strange Godly Shard').rarity('EPIC')

	e.create('godly_shard_flaming_charged').displayName('Charged Flaming Shard').rarity('EPIC')
	e.create('godly_shard_toxic_charged').displayName('Charged Toxic Shard').rarity('EPIC')
	e.create('godly_shard_end_charged').displayName('Charged Ender Shard').rarity('EPIC')
	e.create('godly_shard_abyssal_charged').displayName('Charged Abyssal Shard').rarity('EPIC')
	e.create('godly_shard_strange_charged').displayName('Charged Strange Shard').rarity('EPIC')

	e.create('botanic_godly_alloy').displayName('Botanic Godly Alloy').rarity('EPIC')
	e.create('kinetic_godly_alloy').displayName('Kinetic Godly Alloy').rarity('EPIC')
	e.create('fluid_godly_alloy').displayName('Fluid Godly Alloy').rarity('EPIC')
	e.create('energy_godly_alloy').displayName('Energy Godly Alloy').rarity('EPIC')
	e.create('unstable_godly_alloy').displayName('Unstable Godly Alloy').rarity('EPIC')
	e.create('incomplete_energy_godly_alloy').displayName('Incomplete Energy Godly Alloy').rarity('EPIC')
	e.create('incomplete_fluid_godly_alloy').displayName('Incomplete Fluid Godly Alloy').rarity('EPIC')
	e.create('incomplete_unstable_godly_alloy').displayName('Incomplete Unstable Godly Alloy').rarity('EPIC')
})
