StartupEvents.registry('item', e => {
	e.create('ht_cupronickel_ingot').displayName('HT Cupronickel Ingot')
	e.create('ht_cupronickel_nugget').displayName('HT Cupronickel Nugget')
	e.create('ht_cupronickel_plate').displayName('HT Cupronickel Plate')
	e.create('ht_ceramic_plate').displayName('HT Ceramic Tile')
	e.create('ht_cupronickel_dust').displayName('HT Cupronickel Dust')
	e.create('ht_cupronickel_coil').displayName('HT Cupronickel Coil')
	e.create('ht_cupronickel_wire').displayName('HT Cupronickel Wire')
	e.create('incomplete_graphite_electrodes_machine_casing').displayName('Incomplete Machine Casing with Graphite Electrodes')
	})