console.info('Loaded arc multiblockblocks (blocks)')

StartupEvents.registry('block', e => {
e.create('machine_casing')
    .displayName('Machine Casing')
    .mapColor('color_gray')
    .soundType('metal')
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .textureAll("kubejs:block/machine_casing")
    .tagBlock('mineable/axe')
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
e.create('heat_proof_casing')
    .displayName('Heat Proof Casing')
    .mapColor('color_brown')
    .soundType('stone')
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .textureAll("kubejs:block/heat_proof_casing")
    .tagBlock('mineable/axe')
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
e.create('electric_macine_casing')
    .displayName('Electric Machine Casing')
    .mapColor('color_red')
    .soundType('metal')
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .textureAll("kubejs:block/electric_machine_casing")
    .tagBlock('mineable/axe')
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
e.create('graphite_electrodes_machine_casing')
    .displayName('Machine Casing with Graphite Electrodes')
    .mapColor('color_red')
    .soundType('metal')
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .model("kubejs:block/graphite_electrodes_machine_casing")
    .tagBlock('mineable/axe')
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
})