console.info('FUMO LOADED)')

StartupEvents.registry('block', e => {
	e.create('zalkat_fumo','cardinal')
        .displayName('ZalkaT Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
	e.create('thesauce_fumo','cardinal')
        .displayName('THESAUCE Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('veruty_fumo','cardinal')
        .displayName('Veruty Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('EPIC')})
    e.create('blockypanda83_fumo','cardinal')
        .displayName('Blockypanda83 Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('chaoscorporation_fumo','cardinal')
        .displayName('ChaosCorporation Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('juwny_fumo','cardinal')
        .displayName('juwny Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('m3chanicb_fumo','cardinal')
        .displayName('M3chanicB Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('not_vi789_fumo','cardinal')
        .displayName('Not_Vi789 Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('sirheadcrab1_fumo','cardinal')
        .displayName('Sirheadcrab1 Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('spar117maschief_fumo','cardinal')
        .displayName('spar117maschief Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})

})	
