console.info('FUMO LOADED)')

StartupEvents.registry('block', e => {
    e.create('alice_fumo','cardinal')
        .displayName('Alice Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('blackreimu_fumo','cardinal')
        .displayName('Black Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('bluereimu_fumo','cardinal')
        .displayName('Blue Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('brownreimu_fumo','cardinal')
        .displayName('Brown Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('chen_fumo','cardinal')
        .displayName('Chen Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('cirno_fumo','cardinal')
        .displayName('Cirno Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('cyanreimu_fumo','cardinal')
        .displayName('Cyan Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('debug_fumo','cardinal')
        .displayName('Debug Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('eiki_fumo','cardinal')
        .displayName('Eiki Shiki Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('flandre_fumo','cardinal')
        .displayName('Flandre Scarlet Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('grayreimu_fumo','cardinal')
        .displayName('Gray Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('greenreimu_fumo','cardinal')
        .displayName('Green Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('koishi_fumo','cardinal')
        .displayName('Koishi Komeiji Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('lightbluereimu_fumo','cardinal')
        .displayName('Light Blue Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
	e.create('limereimu_fumo','cardinal')
        .displayName('Lime Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('magentareimu_fumo','cardinal')
        .displayName('Magenta Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('marisa_fumo','cardinal')
        .displayName('Hatless Marisa Kirisame Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('marisahat_fumo','cardinal')
        .displayName('Marisa Kirisame Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('meiling_fumo','cardinal')
        .displayName('Meiling Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('nazrin_fumo','cardinal')
        .displayName('Nazrin Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('newreimu_fumo','cardinal')
        .displayName('Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')	
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('nitori_fumo','cardinal')
        .displayName('Nitori Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('offcolorreimu_fumo','cardinal')
        .displayName('Off-color Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('orangereimu_fumo','cardinal')
        .displayName('Orange Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('patchouli_fumo','cardinal')
        .displayName('Patchouli Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('pinkreimu_fumo','cardinal')
        .displayName('Pink Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('purplereimu_fumo','cardinal')
        .displayName('Purple Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('reimu_fumo','cardinal')
        .displayName('Bootleg Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('sunnymilk_fumo','cardinal')
        .displayName('Sunny Milk Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('tancirno_fumo','cardinal')
        .displayName('Tan Cirno Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('tewi_fumo','cardinal')
        .displayName('Tewi Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('whitereimu_fumo','cardinal')
        .displayName('White Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('yellowreimu_fumo','cardinal')
        .displayName('Yellow Reimu Hakurei Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.tagBlock('kubejs:reimu_colorable')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('youmu_fumo','cardinal')
        .displayName('Youmu Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
    e.create('yuyuko_fumo','cardinal')
        .displayName('Yuyuko Fumo')
		.fullBlock(false)
		.waterlogged()
		.box(4, 0, 4, 12, 16, 12, true)
		.defaultCutout()
		.noCollision()
		.tagBlock('minecraft:mineable/shears')
		.soundType(SoundType.WOOL)
		.tagItem('kubejs:fumo')
		.item(item => {item.unstackable()})
		.item(item => {item.rarity('RARE')})
})	