StartupEvents.registry('block', e => {
        e.create('steel_block')
        .displayName('Steel Block')
        .soundType('metal')
        .hardness(1.0)
        .resistance(1.0)
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .tagBlock('minecraft:beacon_base_blocks')
        e.create('ht_cupronickel_block')
        .displayName('HT Cupronickel Block')
        .soundType('metal')
        .hardness(1.0)
        .resistance(1.0)
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .tagBlock('minecraft:needs_iron_tool')
        .tagBlock('minecraft:beacon_base_blocks')	
})