#KubeJS Common Properties
#Sun Dec 14 16:11:21 KRAT 2025
matchJsonRecipes=true
allowAsyncStreams=true
announceReload=true
startupErrorGUI=true
serverOnly=false
hideServerScriptErrors=false
saveDevPropertiesInConfig=false
packmode=1
ignoreCustomUniqueRecipeIds=false
creativeModeTabIcon=minecraft\:iron_ingot
startupErrorReportUrl=
