ServerEvents.recipes(e => {
    e.recipes.create.compacting('18x minecraft:iron_nugget', 'create:crushed_raw_iron').heated()
    e.recipes.create.compacting('18x minecraft:gold_nugget', 'create:crushed_raw_gold').heated()
    e.recipes.create.compacting('18x create:copper_nugget', 'create:crushed_raw_copper').heated()
    e.recipes.create.compacting('18x create:zinc_nugget', 'create:crushed_raw_zinc').heated()
    e.recipes.create.compacting('18x thermal:silver_nugget', 'create:crushed_raw_silver').heated()
    e.recipes.create.compacting('18x thermal:tin_nugget', 'create:crushed_raw_tin').heated()
    e.recipes.create.compacting('18x thermal:lead_nugget', 'create:crushed_raw_lead').heated()
    e.recipes.create.compacting('18x immersiveengineering:nugget_aluminum', 'create:crushed_raw_aluminum').heated()
    e.recipes.create.compacting('18x thermal:nickel_nugget', 'create:crushed_raw_nickel').heated()
    e.recipes.create.compacting('2x minecraft:nether_brick', 'minecraft:netherrack').heated()
})