
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1082191
	#The name of the modpack
	modpackName = "Contained Chaos"
	#The version of the modpack
	modpackVersion = "1.9b6"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

