ServerEvents.tags('item', e => {
    e.add('forge:alloys/redstone', 'kubejs:redstone_alloy')
    e.add('forge:alloys/amethyst', 'kubejs:amethyst_alloy')
    e.add('forge:alloys/condensed', 'kubejs:condensed_alloy')
    e.add('forge:alloys/unstable', 'kubejs:unstable_alloy')
	e.add('forge:alloys/godly', 'kubejs:botanic_godly_alloy')
	e.add('forge:alloys/godly', 'kubejs:fluid_godly_alloy')
	e.add('forge:alloys/godly', 'kubejs:energy_godly_alloy')
	e.add('forge:alloys/godly_incomplete', 'kubejs:incomplete_energy_godly_alloy')
	e.add('forge:alloys/godly_incomplete', 'kubejs:incomplete_fluid_godly_alloy')
	e.add('forge:alloys/godly_incomplete', 'kubejs:incomplete_unstable_godly_alloy')
	e.add('forge:alloys/godly', 'kubejs:unstable_godly_alloy')
	e.add('forge:alloys/godly', 'kinetic_godly_alloy')
	e.add('forge:alloys/radiance', 'create:refined_radiance')
	e.add('forge:alloys/shadow', 'create:shadow_steel')
	e.add('forge:alloys/chromatic', 'create:chromatic_compound')
	e.add('forge:alloys', 'kubejs:redstone_alloy')
    e.add('forge:alloys', 'kubejs:amethyst_alloy')
    e.add('forge:alloys', 'kubejs:condensed_alloy')
    e.add('forge:alloys', 'kubejs:unstable_alloy')
	e.add('forge:alloys', 'kubejs:botanic_godly_alloy')
	e.add('forge:alloys', 'kubejs:fluid_godly_alloy')
	e.add('forge:alloys', 'kubejs:energy_godly_alloy')
	e.add('forge:alloys', 'kubejs:unstable_godly_alloy')
	e.add('forge:alloys', 'matter_godly_alloy')
	e.add('forge:alloys', 'kinetic_godly_alloy')
	e.add('forge:alloys', 'create:refined_radiance')
	e.add('forge:alloys', 'create:shadow_steel')
	e.add('forge:alloys', 'create:chromatic_compound')
	
})