ServerEvents.tags('item', e => {
    e.add('forge:alloys', 'kubejs:redstone_alloy')
    e.add('forge:alloys', 'kubejs:amethyst_alloy')
    e.add('forge:alloys', 'kubejs:condensed_alloy')
    e.add('forge:alloys', 'kubejs:unstable_alloy')
	e.add('forge:alloys', 'kubejs:botanic_godly_alloy')
	e.add('forge:alloys', 'kubejs:fluid_godly_alloy')
	e.add('forge:alloys', 'kubejs:energy_godly_alloy')
	e.add('forge:alloys', 'kubejs:incomplete_energy_godly_alloy')
	e.add('forge:alloys', 'kubejs:unstable_godly_alloy')
	e.add('forge:alloys', 'create:refined_radiance')
	e.add('forge:alloys', 'create:shadow_steel')
	e.add('forge:alloys', 'create:chromatic_compound')
})