ServerEvents.tags('item', e => {
    e.add('kubejs:completes_ore_processing_quests', 'minecraft:raw_iron')
    e.add('kubejs:completes_ore_processing_quests', 'minecraft:raw_gold')
    e.add('kubejs:completes_ore_processing_quests', 'minecraft:raw_copper')
    e.add('kubejs:completes_ore_processing_quests', 'minecraft:raw_osmium')
    e.add('kubejs:completes_ore_processing_quests', '#forge:raw_materials/tin')
    e.add('kubejs:completes_ore_processing_quests', '#forge:raw_materials/lead')
    e.add('kubejs:completes_ore_processing_quests', '#forge:raw_materials/uranium')
    e.add('kubejs:completes_ore_processing_quests', '#minecraft:iron_ores')
    e.add('kubejs:completes_ore_processing_quests', '#minecraft:gold_ores')
    e.add('kubejs:completes_ore_processing_quests', '#minecraft:copper_ores')
    e.add('kubejs:completes_ore_processing_quests', '#forge:ores/osmium')
    e.add('kubejs:completes_ore_processing_quests', '#forge:ores/tin')
    e.add('kubejs:completes_ore_processing_quests', '#forge:ores/lead')
    e.add('kubejs:completes_ore_processing_quests', '#forge:ores/uranium')
    e.add('kubejs:completes_ore_processing_quests', '#forge:storage_blocks/raw_iron')
    e.add('kubejs:completes_ore_processing_quests', '#forge:storage_blocks/raw_gold')
    e.add('kubejs:completes_ore_processing_quests', '#forge:storage_blocks/raw_copper')
    e.add('kubejs:completes_ore_processing_quests', '#forge:storage_blocks/raw_osmium')
    e.add('kubejs:completes_ore_processing_quests', '#forge:storage_blocks/raw_tin')
    e.add('kubejs:completes_ore_processing_quests', '#forge:storage_blocks/raw_lead')
    e.add('kubejs:completes_ore_processing_quests', '#forge:storage_blocks/raw_uranium')
})