console.info('Loaded ccc_custom (fluid)')

StartupEvents.registry('fluid', e => {
    e.create('liquid_redstone')
        .thickTexture(0xC90000)
        .bucketColor(0xC90000)
        .displayName('Liquid Redstone')
	e.create('liquid_amethyst')
        .thickTexture(0x71318D)
        .bucketColor(0x71318D)
        .displayName('Destabilized Amethyst')
    e.create('molten_iron')
        .thickTexture(0xC4B7AF)
        .bucketColor(0xC4B7AF)
        .displayName('Molten Iron')
    e.create('molten_moon_cheese')
        .thickTexture(0xFFD91C)
        .bucketColor(0xFFD91C)
        .displayName('Molten Moon Cheese')
})